spring:
  datasource:
    generate-unique-name: false
    name: GoodPc
    url: jdbc:postgresql://localhost:5432/GoodPC
    username: postgres
    password: root

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
logging:
  level:
    org.springframework: ERROR
    io.app: DEBUG





